"""remove_long_memory_table

Revision ID: 4c926c8a125a
Revises: d5b7e1de6779
Create Date: 2026-01-28 22:13:13.964112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c926c8a125a"
down_revision: Union[str, None] = "d5b7e1de6779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: This migration must be resilient when upgrading SQLite databases that
    # were created outside Alembic (e.g. via Base.metadata.create_all()) or have
    # drifted slightly (missing index/table).
    #
    # Using IF EXISTS avoids hard failures like:
    #   sqlite3.OperationalError: no such index: ix_long_memory_user_id
    idx_name = op.f("ix_long_memory_user_id")
    op.execute(sa.text(f"DROP INDEX IF EXISTS {idx_name}"))
    op.execute(sa.text("DROP TABLE IF EXISTS long_memory"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "long_memory",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column("key", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name=op.f("uq_user_memory_key")),
    )
    op.create_index(op.f("ix_long_memory_user_id"), "long_memory", ["user_id"], unique=False)
    # ### end Alembic commands ###
