"""add multi-agent conversation tables

Revision ID: 2567797359b1
Revises: c7d8e9f0a1b2
Create Date: 2026-02-12 13:44:14.301888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2567797359b1'
down_revision: Union[str, None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('telegram_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_creator', 'conversations', ['creator_user_id'], unique=False)
    op.create_index('ix_conversation_status', 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_creator_user_id'), 'conversations', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_telegram_group_id'), 'conversations', ['telegram_group_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('has_agreed', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_participant')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_index('ix_participant_conversation', 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index('ix_participant_user', 'conversation_participants', ['user_id'], unique=False)
    op.create_table('multi_agent_conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('participant_user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('is_private_instruction', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_agent_conversation_messages_conversation_id'), 'multi_agent_conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_multi_agent_conversation_messages_created_at'), 'multi_agent_conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_multi_agent_conversation_messages_participant_user_id'), 'multi_agent_conversation_messages', ['participant_user_id'], unique=False)
    op.create_index('ix_multi_agent_msg_conversation', 'multi_agent_conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_multi_agent_msg_participant', 'multi_agent_conversation_messages', ['participant_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_multi_agent_msg_participant', table_name='multi_agent_conversation_messages')
    op.drop_index('ix_multi_agent_msg_conversation', table_name='multi_agent_conversation_messages')
    op.drop_index(op.f('ix_multi_agent_conversation_messages_participant_user_id'), table_name='multi_agent_conversation_messages')
    op.drop_index(op.f('ix_multi_agent_conversation_messages_created_at'), table_name='multi_agent_conversation_messages')
    op.drop_index(op.f('ix_multi_agent_conversation_messages_conversation_id'), table_name='multi_agent_conversation_messages')
    op.drop_table('multi_agent_conversation_messages')
    op.drop_index('ix_participant_user', table_name='conversation_participants')
    op.drop_index('ix_participant_conversation', table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_conversations_telegram_group_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_creator_user_id'), table_name='conversations')
    op.drop_index('ix_conversation_status', table_name='conversations')
    op.drop_index('ix_conversation_creator', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
